# Source
# https://github.com/iced-rs/iced/blob/master/.github/workflows/build.yml

name: Build
on:
  push:
    branches:
      - gui
    tags:
      - '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get install -y libgtk-3-dev
      - name: Build cracker_gui binary
        run: cargo build --verbose --profile release-opt --package cracker_gui
      - name: Archive cracker_gui binary
        uses: actions/upload-artifact@v1
        with:
          name: bedrock_cracker-x86_64-unknown-linux-gnu
          path: target/release-opt/cracker_gui
  windows:
    runs-on: windows-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Enable static CRT linkage
        run: |
          mkdir .cargo
          echo '[target.x86_64-pc-windows-msvc]' >> .cargo/config
          echo 'rustflags = ["-Ctarget-feature=+crt-static"]' >> .cargo/config
      - name: Run the application without starting the shell
        run: |
          sed -i '1 i\#![windows_subsystem = \"windows\"]' cracker_gui/src/main.rs
      - name: Build cracker_gui binary
        run: cargo build --verbose --profile release-opt --package cracker_gui
      - name: Archive cracker_gui binary
        uses: actions/upload-artifact@v1
        with:
          name: cracker_gui-x86_64-pc-windows-msvc
          path: target/release-opt/cracker_gui.exe

  macos:
    runs-on: macOS-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/checkout@master
      - name: Build cracker_gui binary
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.14
        run: cargo build --verbose --profile release-opt --package cracker_gui
      - name: Open binary via double-click
        run: chmod +x target/release-opt/cracker_gui
      - name: Archive cracker_gui binary
        uses: actions/upload-artifact@v1
        with:
          name: cracker_gui-x86_64-apple-darwin
          path: target/release-opt/cracker_gui


  create_release:
    needs: [linux, windows, macos]
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*